# Generated by Django 5.1.3 on 2025-04-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_alter_patient_created_at_alter_patient_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
