# Generated by Django 5.1.3 on 2025-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_alter_patient_age_alter_patient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
    ]
