# Generated by Django 5.1.3 on 2025-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_alter_patient_age_alter_patient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "M"), ("F", "F")], max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="patient",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
