# Generated by Django 5.1.3 on 2025-04-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0010_alter_patient_age_alter_patient_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
