# Generated by Django 5.1.3 on 2025-04-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0011_alter_patient_age_alter_patient_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
