# Generated by Django 5.1.3 on 2025-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0014_alter_patient_age_alter_patient_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
