# Generated by Django 5.1.3 on 2025-04-05 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0015_alter_patient_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
