# Generated by Django 5.1.3 on 2025-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0017_alter_patient_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
