# Generated by Django 5.1.3 on 2025-04-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0019_remove_patient_updated_at_alter_patient_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
